// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: edges.sql

package storage

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/pgvector/pgvector-go"
)

const buildTagSharedEdges = `-- name: BuildTagSharedEdges :exec
INSERT INTO edges (source_id, target_id, rel_type, weight)
SELECT $1::uuid, nt2.node_id, 'tag_shared',
       COUNT(*)::real / NULLIF((SELECT COUNT(*) FROM node_tags WHERE node_id = $1), 0)
FROM node_tags nt1
JOIN node_tags nt2 ON nt1.tag_id = nt2.tag_id
WHERE nt1.node_id = $1 AND nt2.node_id != $1
GROUP BY nt2.node_id
HAVING COUNT(*) >= 2
ON CONFLICT (source_id, target_id, rel_type) DO UPDATE
SET weight = GREATEST(edges.weight, EXCLUDED.weight)
`

// Create tag_shared edges for nodes sharing 2+ tags with the given node.
// Weight = shared_count / total_tags_on_source_node (normalized 0-1).
func (q *Queries) BuildTagSharedEdges(ctx context.Context, dollar_1 pgtype.UUID) error {
	_, err := q.db.Exec(ctx, buildTagSharedEdges, dollar_1)
	return err
}

const findSimilarNodes = `-- name: FindSimilarNodes :many
SELECT id, title, (1 - (embedding <=> $2::vector))::real AS similarity
FROM nodes
WHERE embedding IS NOT NULL AND id != $3::uuid
ORDER BY embedding <=> $2::vector
LIMIT $1
`

type FindSimilarNodesParams struct {
	Limit     int32           `json:"limit"`
	Embedding pgvector.Vector `json:"embedding"`
	ExcludeID pgtype.UUID     `json:"exclude_id"`
}

type FindSimilarNodesRow struct {
	ID         pgtype.UUID `json:"id"`
	Title      string      `json:"title"`
	Similarity float32     `json:"similarity"`
}

// Find nodes with similar embeddings using pgvector cosine distance.
func (q *Queries) FindSimilarNodes(ctx context.Context, arg FindSimilarNodesParams) ([]FindSimilarNodesRow, error) {
	rows, err := q.db.Query(ctx, findSimilarNodes, arg.Limit, arg.Embedding, arg.ExcludeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindSimilarNodesRow{}
	for rows.Next() {
		var i FindSimilarNodesRow
		if err := rows.Scan(&i.ID, &i.Title, &i.Similarity); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertEdge = `-- name: UpsertEdge :exec
INSERT INTO edges (source_id, target_id, rel_type, weight)
VALUES ($1, $2, $3, $4)
ON CONFLICT (source_id, target_id, rel_type) DO UPDATE
SET weight = GREATEST(edges.weight, EXCLUDED.weight)
`

type UpsertEdgeParams struct {
	SourceID pgtype.UUID `json:"source_id"`
	TargetID pgtype.UUID `json:"target_id"`
	RelType  string      `json:"rel_type"`
	Weight   float32     `json:"weight"`
}

// Create or update edge, keeping the higher weight.
func (q *Queries) UpsertEdge(ctx context.Context, arg UpsertEdgeParams) error {
	_, err := q.db.Exec(ctx, upsertEdge,
		arg.SourceID,
		arg.TargetID,
		arg.RelType,
		arg.Weight,
	)
	return err
}
