// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: jobs.sql

package storage

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimJob = `-- name: ClaimJob :one
UPDATE jobs
SET status = 'running',
    claimed_at = now(),
    attempts = attempts + 1
WHERE id = (
    SELECT id FROM jobs
    WHERE status = 'pending'
      AND scheduled_for <= now()
      AND attempts < max_attempts
    ORDER BY created_at ASC
    FOR UPDATE SKIP LOCKED
    LIMIT 1
)
RETURNING id, type, payload, status, attempts, max_attempts, error,
          created_at, claimed_at, completed_at, scheduled_for
`

type ClaimJobRow struct {
	ID           pgtype.UUID        `json:"id"`
	Type         string             `json:"type"`
	Payload      []byte             `json:"payload"`
	Status       string             `json:"status"`
	Attempts     int32              `json:"attempts"`
	MaxAttempts  int32              `json:"max_attempts"`
	Error        pgtype.Text        `json:"error"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	ClaimedAt    pgtype.Timestamptz `json:"claimed_at"`
	CompletedAt  pgtype.Timestamptz `json:"completed_at"`
	ScheduledFor pgtype.Timestamptz `json:"scheduled_for"`
}

func (q *Queries) ClaimJob(ctx context.Context) (ClaimJobRow, error) {
	row := q.db.QueryRow(ctx, claimJob)
	var i ClaimJobRow
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Payload,
		&i.Status,
		&i.Attempts,
		&i.MaxAttempts,
		&i.Error,
		&i.CreatedAt,
		&i.ClaimedAt,
		&i.CompletedAt,
		&i.ScheduledFor,
	)
	return i, err
}

const completeJob = `-- name: CompleteJob :exec
UPDATE jobs
SET status = 'done', completed_at = now(), error = NULL
WHERE id = $1
`

func (q *Queries) CompleteJob(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, completeJob, id)
	return err
}

const createJob = `-- name: CreateJob :one
INSERT INTO jobs (type, payload, max_attempts)
VALUES ($1, $2, $3)
RETURNING id, type, payload, status, attempts, max_attempts, error,
          created_at, claimed_at, completed_at, scheduled_for
`

type CreateJobParams struct {
	Type        string `json:"type"`
	Payload     []byte `json:"payload"`
	MaxAttempts int32  `json:"max_attempts"`
}

type CreateJobRow struct {
	ID           pgtype.UUID        `json:"id"`
	Type         string             `json:"type"`
	Payload      []byte             `json:"payload"`
	Status       string             `json:"status"`
	Attempts     int32              `json:"attempts"`
	MaxAttempts  int32              `json:"max_attempts"`
	Error        pgtype.Text        `json:"error"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	ClaimedAt    pgtype.Timestamptz `json:"claimed_at"`
	CompletedAt  pgtype.Timestamptz `json:"completed_at"`
	ScheduledFor pgtype.Timestamptz `json:"scheduled_for"`
}

func (q *Queries) CreateJob(ctx context.Context, arg CreateJobParams) (CreateJobRow, error) {
	row := q.db.QueryRow(ctx, createJob, arg.Type, arg.Payload, arg.MaxAttempts)
	var i CreateJobRow
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Payload,
		&i.Status,
		&i.Attempts,
		&i.MaxAttempts,
		&i.Error,
		&i.CreatedAt,
		&i.ClaimedAt,
		&i.CompletedAt,
		&i.ScheduledFor,
	)
	return i, err
}

const failJob = `-- name: FailJob :exec
UPDATE jobs
SET status = CASE WHEN attempts >= max_attempts THEN 'dead' ELSE 'failed' END,
    error = $2,
    completed_at = now()
WHERE id = $1
`

type FailJobParams struct {
	ID    pgtype.UUID `json:"id"`
	Error pgtype.Text `json:"error"`
}

func (q *Queries) FailJob(ctx context.Context, arg FailJobParams) error {
	_, err := q.db.Exec(ctx, failJob, arg.ID, arg.Error)
	return err
}

const insertPendingNode = `-- name: InsertPendingNode :one
INSERT INTO nodes (type, title, content, source_url, status, version)
VALUES ($1, $2, $3, $4, 'pending', 1)
RETURNING id, type, title, content, source_url, status, version, created_at, updated_at
`

type InsertPendingNodeParams struct {
	Type      string      `json:"type"`
	Title     string      `json:"title"`
	Content   pgtype.Text `json:"content"`
	SourceUrl pgtype.Text `json:"source_url"`
}

type InsertPendingNodeRow struct {
	ID        pgtype.UUID        `json:"id"`
	Type      string             `json:"type"`
	Title     string             `json:"title"`
	Content   pgtype.Text        `json:"content"`
	SourceUrl pgtype.Text        `json:"source_url"`
	Status    string             `json:"status"`
	Version   int32              `json:"version"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) InsertPendingNode(ctx context.Context, arg InsertPendingNodeParams) (InsertPendingNodeRow, error) {
	row := q.db.QueryRow(ctx, insertPendingNode,
		arg.Type,
		arg.Title,
		arg.Content,
		arg.SourceUrl,
	)
	var i InsertPendingNodeRow
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Title,
		&i.Content,
		&i.SourceUrl,
		&i.Status,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const retryJob = `-- name: RetryJob :exec
UPDATE jobs
SET status = 'pending',
    scheduled_for = now() + make_interval(secs => $2::double precision)
WHERE id = $1 AND status = 'failed'
`

type RetryJobParams struct {
	ID             pgtype.UUID `json:"id"`
	BackoffSeconds float64     `json:"backoff_seconds"`
}

func (q *Queries) RetryJob(ctx context.Context, arg RetryJobParams) error {
	_, err := q.db.Exec(ctx, retryJob, arg.ID, arg.BackoffSeconds)
	return err
}
