// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package storage

import (
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/pgvector/pgvector-go"
)

type DiscoveryRun struct {
	ID            pgtype.UUID        `json:"id"`
	RunType       string             `json:"run_type"`
	Results       []byte             `json:"results"`
	NodesAffected int32              `json:"nodes_affected"`
	EdgesCreated  int32              `json:"edges_created"`
	ExecutedAt    pgtype.Timestamptz `json:"executed_at"`
}

type Edge struct {
	ID        pgtype.UUID        `json:"id"`
	SourceID  pgtype.UUID        `json:"source_id"`
	TargetID  pgtype.UUID        `json:"target_id"`
	RelType   string             `json:"rel_type"`
	Weight    float32            `json:"weight"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Job struct {
	ID           pgtype.UUID        `json:"id"`
	Type         string             `json:"type"`
	Payload      []byte             `json:"payload"`
	Status       string             `json:"status"`
	Attempts     int32              `json:"attempts"`
	MaxAttempts  int32              `json:"max_attempts"`
	ClaimedAt    pgtype.Timestamptz `json:"claimed_at"`
	CompletedAt  pgtype.Timestamptz `json:"completed_at"`
	ScheduledFor pgtype.Timestamptz `json:"scheduled_for"`
	Error        pgtype.Text        `json:"error"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type Node struct {
	ID        pgtype.UUID        `json:"id"`
	Type      string             `json:"type"`
	Title     string             `json:"title"`
	Content   pgtype.Text        `json:"content"`
	Summary   pgtype.Text        `json:"summary"`
	SourceUrl pgtype.Text        `json:"source_url"`
	ImageKey  pgtype.Text        `json:"image_key"`
	Embedding pgvector.Vector    `json:"embedding"`
	Version   int32              `json:"version"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	Status    string             `json:"status"`
}

type NodeTag struct {
	NodeID     pgtype.UUID   `json:"node_id"`
	TagID      pgtype.UUID   `json:"tag_id"`
	Confidence pgtype.Float4 `json:"confidence"`
}

type ReviewSchedule struct {
	NodeID     pgtype.UUID        `json:"node_id"`
	Stability  float32            `json:"stability"`
	Difficulty float32            `json:"difficulty"`
	DueDate    pgtype.Timestamptz `json:"due_date"`
	LastReview pgtype.Timestamptz `json:"last_review"`
	Reps       int32              `json:"reps"`
	Lapses     int32              `json:"lapses"`
	State      string             `json:"state"`
}

type Tag struct {
	ID   pgtype.UUID `json:"id"`
	Name string      `json:"name"`
}
