// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: nodes.sql

package storage

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteNode = `-- name: DeleteNode :exec
DELETE FROM nodes WHERE id = $1
`

func (q *Queries) DeleteNode(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteNode, id)
	return err
}

const listNodes = `-- name: ListNodes :many
SELECT id, title, source_url, created_at
FROM nodes
WHERE ($2::TIMESTAMPTZ IS NULL OR created_at < $2)
ORDER BY created_at DESC
LIMIT $1
`

type ListNodesParams struct {
	Limit  int32              `json:"limit"`
	Cursor pgtype.Timestamptz `json:"cursor"`
}

type ListNodesRow struct {
	ID        pgtype.UUID        `json:"id"`
	Title     string             `json:"title"`
	SourceUrl pgtype.Text        `json:"source_url"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListNodes(ctx context.Context, arg ListNodesParams) ([]ListNodesRow, error) {
	rows, err := q.db.Query(ctx, listNodes, arg.Limit, arg.Cursor)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListNodesRow{}
	for rows.Next() {
		var i ListNodesRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.SourceUrl,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentNodes = `-- name: ListRecentNodes :many
SELECT id, title, source_url, created_at
FROM nodes
ORDER BY created_at DESC
LIMIT $1
`

type ListRecentNodesRow struct {
	ID        pgtype.UUID        `json:"id"`
	Title     string             `json:"title"`
	SourceUrl pgtype.Text        `json:"source_url"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListRecentNodes(ctx context.Context, limit int32) ([]ListRecentNodesRow, error) {
	rows, err := q.db.Query(ctx, listRecentNodes, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRecentNodesRow{}
	for rows.Next() {
		var i ListRecentNodesRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.SourceUrl,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertRawNode = `-- name: UpsertRawNode :one
INSERT INTO nodes (type, title, content, source_url)
VALUES ($1, $2, $3, $4)
ON CONFLICT (source_url) WHERE source_url IS NOT NULL
DO UPDATE SET title = EXCLUDED.title,
             content = EXCLUDED.content,
             updated_at = now()
RETURNING id, type, title, source_url, created_at, updated_at,
          (xmax = 0) AS created
`

type UpsertRawNodeParams struct {
	Type      string      `json:"type"`
	Title     string      `json:"title"`
	Content   pgtype.Text `json:"content"`
	SourceUrl pgtype.Text `json:"source_url"`
}

type UpsertRawNodeRow struct {
	ID        pgtype.UUID        `json:"id"`
	Type      string             `json:"type"`
	Title     string             `json:"title"`
	SourceUrl pgtype.Text        `json:"source_url"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	Created   bool               `json:"created"`
}

func (q *Queries) UpsertRawNode(ctx context.Context, arg UpsertRawNodeParams) (UpsertRawNodeRow, error) {
	row := q.db.QueryRow(ctx, upsertRawNode,
		arg.Type,
		arg.Title,
		arg.Content,
		arg.SourceUrl,
	)
	var i UpsertRawNodeRow
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Title,
		&i.SourceUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Created,
	)
	return i, err
}
