// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: nodes.sql

package storage

import (
	"context"

	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgtype"
)

const deleteNode = `-- name: DeleteNode :exec
DELETE FROM nodes WHERE id = $1
`

func (q *Queries) DeleteNode(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteNode, id)
	return err
}

const deleteNodeReturningTag = `-- name: DeleteNodeReturningTag :execresult
DELETE FROM nodes WHERE id = $1
`

func (q *Queries) DeleteNodeReturningTag(ctx context.Context, id pgtype.UUID) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, deleteNodeReturningTag, id)
}

const getNode = `-- name: GetNode :one
SELECT id, type, title, content, summary, source_url, image_key, status, version, created_at, updated_at
FROM nodes WHERE id = $1
`

type GetNodeRow struct {
	ID        pgtype.UUID        `json:"id"`
	Type      string             `json:"type"`
	Title     string             `json:"title"`
	Content   pgtype.Text        `json:"content"`
	Summary   pgtype.Text        `json:"summary"`
	SourceUrl pgtype.Text        `json:"source_url"`
	ImageKey  pgtype.Text        `json:"image_key"`
	Status    string             `json:"status"`
	Version   int32              `json:"version"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetNode(ctx context.Context, id pgtype.UUID) (GetNodeRow, error) {
	row := q.db.QueryRow(ctx, getNode, id)
	var i GetNodeRow
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Title,
		&i.Content,
		&i.Summary,
		&i.SourceUrl,
		&i.ImageKey,
		&i.Status,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listNodes = `-- name: ListNodes :many
SELECT id, type, title, content, summary, source_url, image_key, status, version, created_at, updated_at
FROM nodes
WHERE ($2::TIMESTAMPTZ IS NULL OR
      (created_at, id) < ($2::TIMESTAMPTZ, $3::uuid))
ORDER BY created_at DESC, id DESC
LIMIT $1
`

type ListNodesParams struct {
	Limit      int32              `json:"limit"`
	CursorTime pgtype.Timestamptz `json:"cursor_time"`
	CursorID   pgtype.UUID        `json:"cursor_id"`
}

type ListNodesRow struct {
	ID        pgtype.UUID        `json:"id"`
	Type      string             `json:"type"`
	Title     string             `json:"title"`
	Content   pgtype.Text        `json:"content"`
	Summary   pgtype.Text        `json:"summary"`
	SourceUrl pgtype.Text        `json:"source_url"`
	ImageKey  pgtype.Text        `json:"image_key"`
	Status    string             `json:"status"`
	Version   int32              `json:"version"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListNodes(ctx context.Context, arg ListNodesParams) ([]ListNodesRow, error) {
	rows, err := q.db.Query(ctx, listNodes, arg.Limit, arg.CursorTime, arg.CursorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListNodesRow{}
	for rows.Next() {
		var i ListNodesRow
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Title,
			&i.Content,
			&i.Summary,
			&i.SourceUrl,
			&i.ImageKey,
			&i.Status,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentNodes = `-- name: ListRecentNodes :many
SELECT id, type, title, content, summary, source_url, image_key, status, version, created_at, updated_at
FROM nodes
ORDER BY created_at DESC
LIMIT $1
`

type ListRecentNodesRow struct {
	ID        pgtype.UUID        `json:"id"`
	Type      string             `json:"type"`
	Title     string             `json:"title"`
	Content   pgtype.Text        `json:"content"`
	Summary   pgtype.Text        `json:"summary"`
	SourceUrl pgtype.Text        `json:"source_url"`
	ImageKey  pgtype.Text        `json:"image_key"`
	Status    string             `json:"status"`
	Version   int32              `json:"version"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListRecentNodes(ctx context.Context, limit int32) ([]ListRecentNodesRow, error) {
	rows, err := q.db.Query(ctx, listRecentNodes, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRecentNodesRow{}
	for rows.Next() {
		var i ListRecentNodesRow
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Title,
			&i.Content,
			&i.Summary,
			&i.SourceUrl,
			&i.ImageKey,
			&i.Status,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateNodeContent = `-- name: UpdateNodeContent :exec
UPDATE nodes
SET content = $2, status = 'processed', updated_at = now()
WHERE id = $1
`

type UpdateNodeContentParams struct {
	ID      pgtype.UUID `json:"id"`
	Content pgtype.Text `json:"content"`
}

func (q *Queries) UpdateNodeContent(ctx context.Context, arg UpdateNodeContentParams) error {
	_, err := q.db.Exec(ctx, updateNodeContent, arg.ID, arg.Content)
	return err
}

const updateNodeStatus = `-- name: UpdateNodeStatus :exec
UPDATE nodes
SET status = $2, updated_at = now()
WHERE id = $1
`

type UpdateNodeStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
}

func (q *Queries) UpdateNodeStatus(ctx context.Context, arg UpdateNodeStatusParams) error {
	_, err := q.db.Exec(ctx, updateNodeStatus, arg.ID, arg.Status)
	return err
}

const upsertRawNode = `-- name: UpsertRawNode :one
INSERT INTO nodes (type, title, content, source_url)
VALUES ($1, $2, $3, $4)
ON CONFLICT (source_url) WHERE source_url IS NOT NULL
DO UPDATE SET title = EXCLUDED.title,
             content = EXCLUDED.content,
             updated_at = now()
RETURNING id, type, title, source_url, status, created_at, updated_at,
          (xmax = 0) AS created
`

type UpsertRawNodeParams struct {
	Type      string      `json:"type"`
	Title     string      `json:"title"`
	Content   pgtype.Text `json:"content"`
	SourceUrl pgtype.Text `json:"source_url"`
}

type UpsertRawNodeRow struct {
	ID        pgtype.UUID        `json:"id"`
	Type      string             `json:"type"`
	Title     string             `json:"title"`
	SourceUrl pgtype.Text        `json:"source_url"`
	Status    string             `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	Created   bool               `json:"created"`
}

func (q *Queries) UpsertRawNode(ctx context.Context, arg UpsertRawNodeParams) (UpsertRawNodeRow, error) {
	row := q.db.QueryRow(ctx, upsertRawNode,
		arg.Type,
		arg.Title,
		arg.Content,
		arg.SourceUrl,
	)
	var i UpsertRawNodeRow
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Title,
		&i.SourceUrl,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Created,
	)
	return i, err
}
