// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tags.sql

package storage

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const associateNodeTag = `-- name: AssociateNodeTag :exec
INSERT INTO node_tags (node_id, tag_id, confidence)
VALUES ($1, $2, $3)
ON CONFLICT (node_id, tag_id) DO UPDATE
SET confidence = GREATEST(node_tags.confidence, EXCLUDED.confidence)
`

type AssociateNodeTagParams struct {
	NodeID     pgtype.UUID   `json:"node_id"`
	TagID      pgtype.UUID   `json:"tag_id"`
	Confidence pgtype.Float4 `json:"confidence"`
}

// Link node to tag with confidence score, keep highest confidence on conflict.
func (q *Queries) AssociateNodeTag(ctx context.Context, arg AssociateNodeTagParams) error {
	_, err := q.db.Exec(ctx, associateNodeTag, arg.NodeID, arg.TagID, arg.Confidence)
	return err
}

const getNodeTags = `-- name: GetNodeTags :many
SELECT t.id, t.name, nt.confidence
FROM tags t JOIN node_tags nt ON t.id = nt.tag_id
WHERE nt.node_id = $1
ORDER BY nt.confidence DESC
`

type GetNodeTagsRow struct {
	ID         pgtype.UUID   `json:"id"`
	Name       string        `json:"name"`
	Confidence pgtype.Float4 `json:"confidence"`
}

// Get all tags for a node ordered by confidence.
func (q *Queries) GetNodeTags(ctx context.Context, nodeID pgtype.UUID) ([]GetNodeTagsRow, error) {
	rows, err := q.db.Query(ctx, getNodeTags, nodeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetNodeTagsRow{}
	for rows.Next() {
		var i GetNodeTagsRow
		if err := rows.Scan(&i.ID, &i.Name, &i.Confidence); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertTag = `-- name: UpsertTag :one
INSERT INTO tags (name) VALUES ($1)
ON CONFLICT (name) DO UPDATE SET name = EXCLUDED.name
RETURNING id, name
`

// Insert tag, return existing if name conflict.
func (q *Queries) UpsertTag(ctx context.Context, name string) (Tag, error) {
	row := q.db.QueryRow(ctx, upsertTag, name)
	var i Tag
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}
